### ISSUE TITLE
breaks down when link contains symbol `[`

### ISSUE THREAD

**Issue by yuchen-lea** [stardiviner/org-link-beautify#6]
issue demo:
<img width="956" alt="image" src="https://user-images.githubusercontent.com/7555085/103169598-2c36db00-4878-11eb-97dc-d3e74404ecb4.png">

**Comment by stardiviner** [comment]
I tested with `[[file:/path/to/[kk].jpg]]` in Org without `org-link-beautify`. The `[` is not parsed correctly in Org-mode by default. So this is not a problem of `org-link-beautify`.
Suggest you ask this question in org-mode mailing list.

**Comment by stardiviner** [comment]
注意到我的链接中有 `[` 也没问题啊。

![image](https://user-images.githubusercontent.com/378699/103392937-1c124a80-4b5b-11eb-8969-a0a707dab4d1.png)

可能是你链接有什么特别的地方
