### ISSUE TITLE
Can not click the link in org-link-beautify-mode

### ISSUE THREAD

**Issue by yuchen-lea** [stardiviner/org-link-beautify#7]
Opening links can be performed by both clicking and entering <RET>  after requiring 'org-mouse. 
 It seems in org-link-beautify-mode, Links can be open only by key, not by mouse.

Demo:
![org-link-beautify-bug](https://user-images.githubusercontent.com/7555085/104283044-e8380d00-54ea-11eb-844b-4606851085e7.gif)

Environment:

tested in doom/sandbox: vanilla Doom (only Doom core)    

```
SYSTEM  type       darwin
        config     x86_64-apple-darwin19.6.0
        version    27.1
        build      Dec 16, 2020
        features   NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER 
DOOM    dir        ~/.doom.d/
        version    2.0.9
        theme      doom-peacock
        build      HEAD -> develop 0c9256411 2020-12-15 04:14:40 -0500
```

**Comment by stardiviner** [comment]
This seems caused by I try to add new keymap on org-link-beautify text-property object through function `org-link-beautify--add-keymap`. I will figure out a way to adding keybinding back. If no good solution yet, I will revert this function.

**Comment by stardiviner** [comment]
推送了修复，你试一下。我测试，如果不是图片预览形式的链接，只是icon, 那现在的修复是可以点击的。但是图片预览类型链接还是不能点击。稍后改进下。

**Comment by stardiviner** [comment]
问到了，为什么无法点击图片了。问题解决了，网络不顺畅缘故，新commit还在推送中。 @yuchen-lea

**Comment by yuchen-lea** [comment]
因为刚刚升级emacs和doom-emacs，稍微排查了下问题，但是现在似乎完全不起作用了……

测试环境： doom/sandbox - vanilla emacs，只require org-link-beautify-mode

![bug](https://user-images.githubusercontent.com/7555085/104662087-fc575680-5704-11eb-960e-515756ba5426.gif)


```
SYSTEM  type       darwin
        config     x86_64-apple-darwin19.6.0
        shell      /bin/zsh
        uname      Darwin 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
        path       (~/.emacs.d/bin/ ~/.emacs.d/bin/ ~/.pyenv/shims /opt/local/bin /opt/local/sbin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Library/TeX/texbin ~/.emacs.d/bin /opt/local/bin /opt/local/sbin /usr/local/Caskroom/krita/4.4.1/krita.app/Contents/MacOS/ /usr/local/Cellar/emacs-mac/emacs-27.1-mac-8.1/libexec/emacs/27.1/x86_64-apple-darwin19.6.0/)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Jan 15, 2021
        buildopts  --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-mac/emacs-27.1-mac-8.1/share/info/emacs --prefix=/usr/local/Cellar/emacs-mac/emacs-27.1-mac-8.1 --with-mac --enable-mac-app=/usr/local/Cellar/emacs-mac/emacs-27.1-mac-8.1 --with-gnutls --with-modules
        features   NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER GMP
        traits     (gui server-running envvar-file)
```

**Comment by stardiviner** [comment]
由于之前的实现会产生大量的来自 `all-the-icons` 调用 `memoize` 生成的 timers.
看这里:
- https://emacs.stackexchange.com/questions/62331/why-my-org-link-beautify-extension-generated-many-timers
- https://emacs-china.org/t/timers/15630

所以我修改了实现，现在就不会产生很多timer了。不过现在的实现是基于headline是否打开折叠的state.刚打开文件不是overview 或者fold状态的，需要手动fold一下headline, 再unfold. 但是有的时候貌似这个minor-mode启动了也不生效。需要重新enable 下minor-mode. 这两点都还有待改进。已在todo列表。

**Comment by yuchen-lea** [comment]
![bug](https://user-images.githubusercontent.com/7555085/104731549-d10d4f80-5776-11eb-8c3f-275c4a45d977.gif)

感谢迅速地改进！但是目前问题似乎变多了 😂

- 折叠时会影响不相关heading的链接样式
- 内置链接有的美化，有的没有美化
- 自定义连接不能正常渲染

**Comment by stardiviner** [comment]
恩恩，我也发现这个bug了。我在考虑是否要revert.但是又不舍得辛苦添加的改进机制。哎，难以取舍，现在先考虑能不能修复bug,实在不能，那就revert.

**Comment by stardiviner** [comment]
我知道你也会elisp,你也可以试试解决下这个些bug

**Comment by stardiviner** [comment]
All bugs should be fixed now. Test again with latest update. If you got any new problem. Open new issue.
