### ISSUE TITLE
可否设置切换pdf，video等的预览功能

### ISSUE THREAD

**Issue by xiaolaoc** [stardiviner/org-link-beautify#8]
有时候不想预览，而是显示链接，然后显示比如pdf的图标，而不是直接预览，可否加个这个功能呢？
另外还有个问题，链接的文件如果名字中有空格或者特殊符号，会导致链接失败或显示异常

**Comment by stardiviner** [comment]
不想预览，而是要显示链接，直接执行 `org-link-beautify-mode` 来关闭mode就行。相当于手动关闭。
文件含有空格是不会导致预览失败的。估计是你的Org Mode设置有问题。
特殊符号是什么符号？
